$ ->
  if $('#new-post-form, #sign-up-form, #edit-profile-form').length
    window.cityList = [
      "New York",
      "Los Angeles",
      "Chicago",
      "Houston",
      "Philadelphia",
      "Phoenix",
      "San Diego",
      "San Antonio",
      "Dallas",
      "Detroit",
      "San Jose",
      "Indianapolis",
      "San Francisco",
      "Columbus",
      "Austin",
      "Memphis",
      "Baltimore",
      "Charlotte",
      "Boston",
      "Milwaukee",
      "Washington D.C",
      "Seattle",
      "Washington",
      "Denver",
      "Las Vegas",
      "Portland",
      "Oklahoma City",
      "Atlanta",
      "Kansas City",
      "New Orleans",
      "Cleveland",
      "Omaha",
      "Colorado Springs",
      "Oakland",
      "Miami",
      "Minneapolis",
      "Honolulu",
      "St. Louis",
      "Cincinnati",
      "Tampa",
      "Pittsburgh",
      "Aurora Colorado",
      "Anchorage",
      "Newark",
      "Jersey City",
      "Orlando",
      "Reno",
      "vancouver",
      "Toronto",
      "Moscow",
      "London",
      "Berlin",
      "Madrid",
      "Rome",
      "Paris",
      "Bucharest",
      "Vienna",
      "Hamburg",
      "Budapest",
      "Warsaw",
      "Barcelona",
      "kiev",
      "Milan",
      "Munich",
      "Prague",
      "Sofia",
      "Brussels",
      "Stockholm",
      "Amsterdam",
      "Zagreb",
      "Riga",
      "Athens",
      "Helsinki",
      "Copenhagen",
      "Lisbon",
      "Vilnius",
      "Dublin",
      "Tallinn",
      "Bratislava",
      "Mexico City",
      "Sao Paulo",
      "Buenos Aires",
      "Río de Janeiro",
      "Lima",
      "Santiago",
      "Caracas",
      "Montevideo",
      "Port-au-Prince",
      "La Paz",
      "San Juan",
      "Tokyo",
      "Seoul",
      "Shanghai",
      "Beijing",
      "GuangZhou",
      "Hongkong",
      "Jakarta",
      "Manila",
      "Singapore",
      "Mumbai",
      "Osaka",
      "Shenzhen",
      "HangZhou",
      "ChengDu",
      "Taipei",
      "Bangkok",
      "Ho Chi Minh City",
      "Syndey",
      "Melbourne",
      "Wellington",
      "Auckland"
    ]

    window.collegeList = [
      "Harvard University",
      "Stanford University",
      "University of California Berkeley",
      "Massachusetts Institute of Technology",
      "University of Cambridge",
      "California Institute of Technology",
      "Princeton University",
      "Columbia University",
      "University of Chicago",
      "University of Oxford",
      "Yale University",
      "University of California Los Angeles",
      "Cornell University",
      "University of California San Diego",
      "University of Pennsylvania",
      "University of Washington",
      "The Johns Hopkins University",
      "University of California San Francisco",
      "University of Wisconsin Madison",
      "Swiss Federal Institute of Technology Zurich",
      "The University of Tokyo",
      "University College London",
      "University of Michigan Ann Arbor",
      "The Imperial College of Science Technology and Medicine",
      "University of Illinois at Urbana Champaign",
      "Kyoto University",
      "New York University",
      "University of Toronto",
      "University of Minnesota Twin Cities",
      "Northwestern University",
      "Duke University",
      "Washington University in St Louis",
      "University of Colorado at Boulder",
      "Rockefeller University",
      "University of California Santa Barbara",
      "The University of Texas at Austin",
      "Pierre and Marie Curie University Paris",
      "University of Maryland College Park",
      "University of Paris Sud",
      "University of British Columbia",
      "The University of Manchester",
      "University of Copenhagen",
      "University of North Carolina at Chapel Hill",
      "Karolinska Institute",
      "University of California Irvine",
      "The University of Texas Southwestern Medical Center at Dallas",
      "University of California Davis",
      "University of Southern California",
      "Vanderbilt University",
      "Technical University Munich",
      "The University of Edinburgh",
      "Carnegie Mellon University",
      "Utrecht University",
      "Pennsylvania State University University Park",
      "University of Heidelberg",
      "University of Melbourne",
      "Purdue University west Lafayette",
      "McGill University",
      "The Hebrew University of Jerusalem",
      "University of Zurich",
      "Rutgers The State University of New Jersey",
      "University of Munich",
      "University of Pittsburgh",
      "University of Bristol",
      "The Ohio State University Columbus",
      "The Australian National University",
      "Brown University",
      "King's College London",
      "University of Geneva",
      "University of Oslo",
      "Ecole Normale Superieure Paris",
      "University of Florida",
      "Uppsala University",
      "Leiden University",
      "Boston University",
      "University of Helsinki",
      "Technion Israel Institute of Technology",
      "University of Arizona",
      "Arizona State University Tempe",
      "Moscow State University",
      "Aarhus University",
      "Stockholm University",
      "University of Basel",
      "University of Nottingham",
      "Ghent University",
      "Indiana University Bloomington",
      "Osaka University",
      "The University of Queensland",
      "University of Utah",
      "University of Rochester",
      "The University of Western Australia",
      "McMaster University",
      "Michigan State University",
      "Rice University",
      "University of Groningen",
      "Weizmann Institute of Science",
      "University of Strasbourg",
      "University of Sydney",
      "Case Western Reserve University",
      "University of Freiburg",
      "Baylor College of Medicine",
      "Catholic University of Leuven",
      "Catholic University of Louvain",
      "Emory University",
      "Georgia Institute of Technology",
      "Hokkaido University",
      "Joseph Fourier University",
      "London School of Economics and Political Science",
      "Lund University",
      "Mayo Medical School",
      "Monash University",
      "Nagoya University",
      "National Taiwan University",
      "National University of Singapore",
      "Oregon State University",
      "Radboud University Nijmegen",
      "Seoul National University",
      "Swiss Federal Institute of Technology of Lausanne",
      "Tel Aviv University",
      "Texas A&M University College Station",
      "The University of Georgia",
      "The University of Sheffield",
      "Tohoku University",
      "Tokyo Institute of Technology",
      "Tufts University",
      "University Libre Bruxelles",
      "University of Alberta",
      "University of Amsterdam",
      "University of Birmingham",
      "University of Bonn",
      "University of California Riverside",
      "University of California Santa Cruz",
      "University of Frankfurt",
      "University of Goettingen",
      "University of Iowa",
      "University of Liverpool",
      "University of Massachusetts Amherst",
      "University of Massachusetts Medical School Worcester",
      "University of Montreal",
      "University of Muenster",
      "University of New South Wales",
      "University of Paris Diderot",
      "University of Pisa",
      "University of Roma La Sapienza",
      "University of Sao Paulo",
      "University of Sussex",
      "University of Virginia",
      "University of Wageningen",
      "VU University Amsterdam",
      "Aix Marseille University",
      "Cardiff University",
      "Colorado State University",
      "Dartmouth College",
      "Erasmus University",
      "Florida State University",
      "Fudan University",
      "George Mason University",
      "Iowa State University",
      "King Saud University",
      "Kyushu University",
      "Mount Sinai School of Medicine",
      "National Autonomous University of Mexico",
      "North Carolina State University Raleigh",
      "Oregon Health and Science University",
      "Peking University",
      "Shanghai Jiao Tong University",
      "State University of New York at Stony Brook",
      "Technical University of Denmark",
      "The Chinese University of Hong Kong",
      "The University of Glasgow",
      "The University of Texas Health Science Center at Houston",
      "Tsinghua University",
      "University of Bern",
      "University of Buenos Aires",
      "University of Delaware",
      "University of Gothenburg",
      "University of Hamburg",
      "University of Hawaii at Manoa",
      "University of Illinois at Chicago",
      "University of Kiel",
      "University of Koeln",
      "University of Leeds",
      "University of Mainz",
      "University of Maryland Baltimore",
      "University of Miami",
      "University of Milan",
      "University of Padua",
      "University of Paris Descartes",
      "University of Southampton",
      "University of Tennessee Knoxville",
      "University of Tsukuba",
      "University of Tuebingen",
      "University of Vienna",
      "University of Warwick",
      "University of Waterloo",
      "University of Wuerzburg",
      "Virginia Commonwealth University",
      "Virginia Polytechnic Institute and State University",
      "Zhejiang University",
      "Autonomous University of Barcelona",
      "Autonomous University of Madrid",
      "Brandeis University",
      "Charles University in Prague",
      "Claude Bernard University Lyon",
      "Complutense University of Madrid",
      "Dalhousie University",
      "Delft University of Technology",
      "Dresden University of Technology",
      "Ecole Normale Superieur Lyon",
      "Ecole Polytechnique",
      "Karlsruhe Institute of Technology",
      "King Abdulaziz University",
      "Kobe University",
      "Korea Advanced Institute of Science and Technology",
      "Laval University",
      "Louisiana State University Baton Rouge",
      "Macquarie University",
      "Medical University of Vienna",
      "Nanjing University",
      "Nanyang Technological University",
      "National Tsing Hua University",
      "Newcastle University",
      "Norwegian University of Science and Technology",
      "Paul Sabatier University",
      "Polytechnic Institute of Milan",
      "Queen Mary University of London",
      "Queen's University",
      "Rensselaer Polytechnic Institute",
      "Royal Institute of Technology",
      "RWTH Aachen University",
      "Scuola Normale Superiore Pisa",
      "Simon Fraser University",
      "State University of New York at Buffalo",
      "Sun Yat sen University",
      "Sungkyunkwan University",
      "Swedish University of Agricultural Sciences",
      "Technical University of Berlin",
      "The George Washington University",
      "The Hong Kong University of Science and Technology",
      "The University of Adelaide",
      "The University of Alabama at Birmingham",
      "The University of Auckland",
      "The University of Calgary",
      "The University of Connecticut Storrs",
      "The University of Dundee",
      "The University of Hong Kong",
      "The University of New Mexico Albuquerque",
      "Thomas Jefferson University",
      "Trinity College Dublin",
      "Umea University",
      "University of Aberdeen",
      "University of Antwerp",
      "University of Barcelona",
      "University of Bergen",
      "University of Bologna",
      "University of Bordeaux",
      "University of Cape Town",
      "University of Central Florida",
      "University of Cincinnati",
      "University of Colorado at Denver",
      "University of Duesseldorf",
      "University of Durham",
      "University of East Anglia",
      "University of Erlangen Nuremberg",
      "University of Exeter",
      "University of Florence",
      "University of Guelph",
      "University of Houston",
      "University of Innsbruck",
      "University of Kansas Lawrence",
      "University of Kentucky",
      "University of Lausanne",
      "University of Leicester",
      "University of Leipzig",
      "University of Liege",
      "University of Lorraine",
      "University of Maastricht",
      "University of Marburg",
      "University of Medicine and Dentistry New Jersey",
      "University of Missouri Columbia",
      "University of Montpellier",
      "University of Nebraska Lincoln",
      "University of Notre Dame",
      "University of Oregon",
      "University of Otago",
      "University of Ottawa",
      "University of Paris Dauphine",
      "University of Saskatchewan",
      "University of Science and Technology of China",
      "University of South Florida",
      "University of Southern Denmark",
      "University of St Andrews",
      "University of Stuttgart",
      "University of Turin",
      "University of York",
      "Washington State University Pullman",
      "Western University",
      "Yeshiva University",
      "Yonsei University",
      "Aristotle University of Thessaloniki",
      "Bar Ilan University",
      "Beijing Normal University",
      "Ben Gurion University of the Negev",
      "Brigham Young University",
      "Chalmers University of Technology",
      "Chang Gung University",
      "China Agricultural University",
      "City University of Hong Kong",
      "City University of New York City College",
      "Clemson University",
      "Eindhoven University of Technology",
      "Eotvos Lorand University",
      "Federal University of Minas Gerais",
      "Federal University of Rio de Janeiro",
      "Flinders University",
      "Georgetown University",
      "Griffith University",
      "Hanyang University",
      "Harbin Institute of Technology",
      "Hiroshima University",
      "Huazhong University of Science and Technology",
      "Indian Institute of Science",
      "Industrial Physics and Chemistry Higher Educational Institution Paris",
      "Jagiellonian University",
      "James Cook University",
      "Jilin University",
      "Kansas State University",
      "Keio University",
      "King Fahd University of Petroleum & Minerals",
      "Korea University",
      "Lancaster University",
      "Linkoping University",
      "Medical University of South Carolina",
      "National and Kapodistrian University of Athens",
      "National Cheng Kung University",
      "National Chiao Tung University",
      "Northeastern University",
      "Okayama University",
      "Pohang University of Science and Technology",
      "Polytechnic University of Valencia",
      "Queen's University Belfast",
      "Saint Louis University",
      "Saint Petersburg State University",
      "San Diego State University",
      "Sao Paulo State University",
      "Shandong University",
      "Sichuan University",
      "State University of Campinas",
      "State University of New York at Albany",
      "State University of New York Health Science Center at Brooklyn",
      "Swinburne University of Technology",
      "Syracuse University",
      "Technical University Darmstadt",
      "Temple University",
      "The Hong Kong Polytechnic University",
      "The University of Montana Missoula",
      "The University of Reading",
      "The University of Texas at Dallas",
      "The University of Texas Health Science Center at San Antonio",
      "Tokyo Medical and Dental University",
      "Tulane University",
      "University College Cork",
      "University College Dublin",
      "University of Bath",
      "University of Belgrade",
      "University of Bochum",
      "University of Genova",
      "University of Giessen",
      "University of Granada",
      "University of Halle Wittenberg",
      "University of Konstanz",
      "University of Lisbon",
      "University of Manitoba",
      "University of Naples Federico II",
      "University of Newcastle",
      "University of Nice Sophia Antipolis",
      "University of Oklahoma Norman",
      "University of Oulu",
      "University of Perugia",
      "University of Pompeu Fabra",
      "University of Porto",
      "University of Regensburg",
      "University of Rhode Island",
      "University of South Carolina Columbia",
      "University of Tasmania",
      "University of the Witwatersrand",
      "University of Turku",
      "University of Twente",
      "University of Ulm",
      "University of Valencia",
      "University of Vermont",
      "University of Victoria",
      "University of Warsaw",
      "University of Wollongong",
      "Vrije University Brussel",
      "Wake Forest University",
      "Waseda University",
      "Wayne State University",
      "Xian Jiao Tong University",
      "Auburn University",
      "Beihang University",
      "Boston College",
      "Cairo University",
      "Carleton University",
      "Catholic University of Chile",
      "Catholic University of Korea",
      "Catholic University of the Sacred Heart",
      "Central South University",
      "China Medical University",
      "Concordia University",
      "Curtin University of Technology",
      "Dalian University of Technology",
      "Drexel University",
      "Ecole National Superieure Mines Paris",
      "Federal University of Rio Grande do Sul",
      "Hannover Medical School",
      "Indiana University Purdue University at Indianapolis",
      "Istanbul University",
      "Kanazawa University",
      "Kent State University",
      "King Abdullah University of Science and Technology",
      "Kyung Hee University",
      "Kyungpook National University",
      "La Trobe University",
      "Lanzhou University",
      "Lehigh University",
      "London School of Hygiene and Tropical Medicine",
      "Massey University",
      "Medical College of Wisconsin",
      "Medical University of Graz",
      "Medical University of Innsbruck",
      "Nagasaki University",
      "Nankai University",
      "National Central University",
      "National Sun Yat Sen University",
      "National Yang Ming University",
      "Niigata University",
      "Osaka City University",
      "Peking Union Medical College",
      "Polytechnic University of Turin",
      "Pusan National University",
      "South China University of Technology",
      "Southeast University",
      "Southern Methodist University",
      "Stockholm School of Economics",
      "Technical University of Braunschweig",
      "Technical University of Lisbon",
      "Texas Tech University",
      "The Open University",
      "The University of Texas Medical Branch at Galveston",
      "The University of Tokushima",
      "Tianjin University",
      "Tongji University",
      "University of Alaska Fairbanks",
      "University of Arkansas at Fayetteville",
      "University of Bayreuth",
      "University of Bielefeld",
      "University of Bremen",
      "University of Canterbury",
      "University of Chile",
      "University of Coimbra",
      "University of Duisburg Essen",
      "University of Eastern Finland",
      "University of Essex",
      "University of Ferrara",
      "University of Graz",
      "University of Haifa",
      "University of Hannover",
      "University of Idaho",
      "University of Jena",
      "University of Jyvaskyla",
      "University of KwaZulu Natal",
      "University of Ljubljana",
      "University of Malaya",
      "University of Maryland Baltimore County",
      "University of Milan Bicocca",
      "University of Nebraska Medical Center",
      "University of New Hampshire Durham",
      "University of Palermo",
      "University of Pavia",
      "University of Quebec",
      "University of Rennes",
      "University of Roma Tor Vergata",
      "University of Sherbrooke",
      "University of Surrey",
      "University of Szeged",
      "University of Technology Sydney",
      "University of Tehran",
      "University of the Basque Country",
      "University of Tromso",
      "University of Wyoming",
      "University of Zagreb",
      "University of Zaragoza",
      "Utah State University",
      "Victoria University of Wellington",
      "Vienna University of Technology",
      "Wuhan University",
      "Xiamen University",
      "York University"
    ]

    $('.city-complete').autocomplete
      source: window.cityList

    $('.college-complete').autocomplete
      source: window.collegeList
